<a href="https://colab.research.google.com/github/hiro106/colab_notebooks_for_learning/blob/main/Copies_and_views.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# https://numpy.org/doc/stable/user/basics.copies.html

In [2]:
import numpy as np

### View

In [25]:
x = np.arange(10)

In [26]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
y = x[1:3] # creates a view

In [28]:
y

array([1, 2])

In [29]:
x[1:3] = [10,11]

In [30]:
x

array([ 0, 10, 11,  3,  4,  5,  6,  7,  8,  9])

In [31]:
y

array([10, 11])

In [33]:
y.base

array([ 0, 10, 11,  3,  4,  5,  6,  7,  8,  9])

In [36]:
y[0]= 5

In [37]:
x

array([ 0,  5, 11,  3,  4,  5,  6,  7,  8,  9])

In [38]:
y.base is x

True

### Copy

In [18]:
x = np.arange(9)

In [19]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
x = np.arange(9).reshape(3, 3)

In [21]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
y = x[[1, 2]]

In [23]:
y

array([[3, 4, 5],
       [6, 7, 8]])

In [17]:
y.base is None

True