<a href="https://colab.research.google.com/github/hiro106/colab_notebooks_for_learning/blob/main/Copies_and_views.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
# https://numpy.org/doc/stable/user/basics.copies.html

In [22]:
import numpy as np

### View

In [23]:
x = np.arange(10)

In [24]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
y = x[1:3] # creates a view

In [26]:
y

array([1, 2])

In [27]:
x[1:3] = [10,11]

In [28]:
x

array([ 0, 10, 11,  3,  4,  5,  6,  7,  8,  9])

In [29]:
y

array([10, 11])

In [30]:
y.base

array([ 0, 10, 11,  3,  4,  5,  6,  7,  8,  9])

In [31]:
y[0]= 5

In [32]:
x

array([ 0,  5, 11,  3,  4,  5,  6,  7,  8,  9])

In [33]:
y.base is x

True

### Copy

In [34]:
x = np.arange(9)

In [35]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
x = np.arange(9).reshape(3, 3)

In [37]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [38]:
x[0]

array([0, 1, 2])

In [40]:
x[[0, 1]]

array([[0, 1, 2],
       [3, 4, 5]])

In [41]:
x[0, 1]

1

In [47]:
x[0][2]

2

In [48]:
x[2][0]

6

In [50]:
x[0][[0,1]]

array([0, 1])

In [18]:
y = x[[1, 2]]

In [54]:
y

array([ 5, 11])

In [20]:
y.base is None

True

In [51]:
x[[1, 2]] = [[10, 11, 12], [13, 14, 15]]

In [52]:
x

array([[ 0,  1,  2],
       [10, 11, 12],
       [13, 14, 15]])

In [53]:
y

array([ 5, 11])