<a href="https://colab.research.google.com/github/hiro106/colab_notebooks_for_learning/blob/main/Copies_and_views.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# https://numpy.org/doc/stable/user/basics.copies.html

In [2]:
import numpy as np

In [3]:
x = np.arange(10)

In [4]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
y = x[1:3] # creates a view

In [6]:
y

array([1, 2])

In [7]:
x[1:3] = [10,11]

In [9]:
x

array([ 0, 10, 11,  3,  4,  5,  6,  7,  8,  9])

In [10]:
y

array([10, 11])