<a href="https://colab.research.google.com/github/hiro106/statistics_ml_cs_learning/blob/main/np_copies_views_reshape_ravel_flatten.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# https://numpy.org/doc/stable/user/basics.copies.html

In [3]:
import numpy as np

## Indexing operations

### View

In [4]:
x = np.arange(10)

In [5]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
y = x[1:3] # creates a view

In [7]:
y

array([1, 2])

In [8]:
x[1:3] = [10,11]

In [9]:
x

array([ 0, 10, 11,  3,  4,  5,  6,  7,  8,  9])

In [10]:
y

array([10, 11])

In [11]:
y.base

array([ 0, 10, 11,  3,  4,  5,  6,  7,  8,  9])

In [12]:
y[0]= 5

In [13]:
x

array([ 0,  5, 11,  3,  4,  5,  6,  7,  8,  9])

In [14]:
y.base is x

True

### Copy

In [15]:
x = np.arange(9)

In [16]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
x = np.arange(9).reshape(3, 3)

In [18]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
x[0]

array([0, 1, 2])

In [20]:
x[[0, 1]]

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
x[0, 1]

1

In [22]:
x[0][2]

2

In [23]:
x[2][0]

6

In [24]:
x[0][[0,1]]

array([0, 1])

In [25]:
y = x[[1, 2]]

In [26]:
y

array([[3, 4, 5],
       [6, 7, 8]])

In [27]:
y.base is None

True

In [28]:
x[[1, 2]] = [[10, 11, 12], [13, 14, 15]]

In [29]:
x

array([[ 0,  1,  2],
       [10, 11, 12],
       [13, 14, 15]])

In [30]:
y

array([[3, 4, 5],
       [6, 7, 8]])

## Other operations

In [31]:
x = np.ones((2, 3))

# https://numpy.org/doc/stable/reference/generated/numpy.ones.html

In [32]:
x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [33]:
y = x.T

In [34]:
y

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [35]:
z = y.view()

In [36]:
z

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [37]:
z.shape

(3, 2)

In [38]:
# z.shape = 6

In [39]:
# What is the difference between contiguous and non-contiguous arrays?
# https://stackoverflow.com/questions/26998223/what-is-the-difference-between-contiguous-and-non-contiguous-arrays

In [40]:
# numpy.reshape
# https://numpy.org/doc/stable/reference/generated/numpy.reshape.html#numpy.reshape

It is not always possible to change the shape of an array without copying the data. If you want an error to be raised when the data is copied, you should assign the new shape to the shape attribute of the array:

In [41]:
a = np.zeros((10, 2))

In [42]:
a

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [43]:
b = a.T

In [44]:
b

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [45]:
c = b.view()

In [46]:
c

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [47]:
c.shape

(2, 10)

In [48]:
# c.shape = (20)

AttributeError: ignored