<a href="https://colab.research.google.com/github/hiro106/colab_notebooks_for_learning/blob/main/np_copies_views_reshape_ravel_flatten.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# https://numpy.org/doc/stable/user/basics.copies.html

In [2]:
import numpy as np

## Indexing operations

### View

In [3]:
x = np.arange(10)

In [4]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
y = x[1:3] # creates a view

In [6]:
y

array([1, 2])

In [7]:
x[1:3] = [10,11]

In [8]:
x

array([ 0, 10, 11,  3,  4,  5,  6,  7,  8,  9])

In [9]:
y

array([10, 11])

In [10]:
y.base

array([ 0, 10, 11,  3,  4,  5,  6,  7,  8,  9])

In [11]:
y[0]= 5

In [12]:
x

array([ 0,  5, 11,  3,  4,  5,  6,  7,  8,  9])

In [13]:
y.base is x

True

### Copy

In [14]:
x = np.arange(9)

In [15]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
x = np.arange(9).reshape(3, 3)

In [17]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
x[0]

array([0, 1, 2])

In [19]:
x[[0, 1]]

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
x[0, 1]

1

In [21]:
x[0][2]

2

In [22]:
x[2][0]

6

In [23]:
x[0][[0,1]]

array([0, 1])

In [24]:
y = x[[1, 2]]

In [25]:
y

array([[3, 4, 5],
       [6, 7, 8]])

In [26]:
y.base is None

True

In [27]:
x[[1, 2]] = [[10, 11, 12], [13, 14, 15]]

In [28]:
x

array([[ 0,  1,  2],
       [10, 11, 12],
       [13, 14, 15]])

In [29]:
y

array([[3, 4, 5],
       [6, 7, 8]])

## Other operations

In [30]:
x = np.ones((2, 3))

# https://numpy.org/doc/stable/reference/generated/numpy.ones.html

In [31]:
x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [32]:
y = x.T

In [33]:
y

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [34]:
z = y.view()

In [35]:
z

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [36]:
z.shape

(3, 2)

In [37]:
# z.shape = 6

AttributeError: ignored