<a href="https://colab.research.google.com/github/hiro106/statistics_ml_cs_learning/blob/main/np_copies_views_reshape_ravel_flatten.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# https://numpy.org/doc/stable/user/basics.copies.html

In [2]:
import numpy as np

## Indexing operations

### View

In [3]:
x = np.arange(10)

In [4]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
y = x[1:3] # creates a view

In [6]:
y

array([1, 2])

In [7]:
x[1:3] = [10,11]

In [8]:
x

array([ 0, 10, 11,  3,  4,  5,  6,  7,  8,  9])

In [9]:
y

array([10, 11])

In [10]:
y.base

array([ 0, 10, 11,  3,  4,  5,  6,  7,  8,  9])

In [11]:
y[0]= 5

In [12]:
x

array([ 0,  5, 11,  3,  4,  5,  6,  7,  8,  9])

In [13]:
y.base is x

True

### Copy

In [14]:
x = np.arange(9)

In [15]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
x = np.arange(9).reshape(3, 3)

In [17]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
x[0]

array([0, 1, 2])

In [19]:
x[[0, 1]]

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
x[0, 1]

1

In [21]:
x[0][2]

2

In [22]:
x[2][0]

6

In [23]:
x[0][[0,1]]

array([0, 1])

In [24]:
y = x[[1, 2]]

In [25]:
y

array([[3, 4, 5],
       [6, 7, 8]])

In [26]:
y.base is None

True

In [27]:
x[[1, 2]] = [[10, 11, 12], [13, 14, 15]]

In [28]:
x

array([[ 0,  1,  2],
       [10, 11, 12],
       [13, 14, 15]])

In [29]:
y

array([[3, 4, 5],
       [6, 7, 8]])

## Other operations

In [30]:
x = np.ones((2, 3))

# https://numpy.org/doc/stable/reference/generated/numpy.ones.html

In [31]:
x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [32]:
y = x.T

In [33]:
y

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [34]:
z = y.view()

In [35]:
z

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [36]:
z.shape

(3, 2)

In [37]:
# z.shape = 6

In [38]:
z.reshape((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [39]:
z

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [40]:
z.reshape(-1)

array([1., 1., 1., 1., 1., 1.])

In [41]:
z

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [42]:
z_minus_one = z.reshape(-1)

In [43]:
z_minus_one

array([1., 1., 1., 1., 1., 1.])

In [44]:
z

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

# Go off on a tangent

## numpy.reshape

In [45]:
# What is the difference between contiguous and non-contiguous arrays?
# https://stackoverflow.com/questions/26998223/what-is-the-difference-between-contiguous-and-non-contiguous-arrays

In [46]:
# numpy.reshape
# https://numpy.org/doc/stable/reference/generated/numpy.reshape.html#numpy.reshape

It is not always possible to change the shape of an array without copying the data. If you want an error to be raised when the data is copied, you should assign the new shape to the shape attribute of the array:

In [47]:
a = np.zeros((10, 2))

In [48]:
a

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [49]:
b = a.T

In [50]:
b

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [51]:
c = b.view()

In [52]:
c

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [53]:
c.shape

(2, 10)

In [54]:
# c.shape = (20)

In [55]:
a = np.arange(6)

In [56]:
a

array([0, 1, 2, 3, 4, 5])

In [57]:
a.reshape((3, 2))

array([[0, 1],
       [2, 3],
       [4, 5]])

In [58]:
a

array([0, 1, 2, 3, 4, 5])

In [59]:
a = np.arange(6).reshape((3, 2))

In [60]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [61]:
np.reshape(a, (2, 3)) # C-like index ordering

array([[0, 1, 2],
       [3, 4, 5]])

In [62]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [63]:
np.reshape(np.ravel(a), (2, 3)) # equivalent to C ravel then C reshape

array([[0, 1, 2],
       [3, 4, 5]])

In [64]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [65]:
np.reshape(a, (2, 3), order='F')

array([[0, 4, 3],
       [2, 1, 5]])

In [66]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [67]:
np.reshape(np.ravel(a, order='F'), (2, 3), order='F')

array([[0, 4, 3],
       [2, 1, 5]])

In [68]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

## Contiguous and Not contiguous / C-like and Fortran-like

In [69]:
# What is the difference between contiguous and non-contiguous arrays?
# https://stackoverflow.com/questions/26998223/what-is-the-difference-between-contiguous-and-non-contiguous-arrays

In [70]:
arr = np.arange(100000000).reshape(10000,10000)

In [71]:
arr

array([[       0,        1,        2, ...,     9997,     9998,     9999],
       [   10000,    10001,    10002, ...,    19997,    19998,    19999],
       [   20000,    20001,    20002, ...,    29997,    29998,    29999],
       ...,
       [99970000, 99970001, 99970002, ..., 99979997, 99979998, 99979999],
       [99980000, 99980001, 99980002, ..., 99989997, 99989998, 99989999],
       [99990000, 99990001, 99990002, ..., 99999997, 99999998, 99999999]])

In [72]:
arr.shape

(10000, 10000)

In [73]:
import datetime

In [74]:
datetime

<module 'datetime' from '/usr/lib/python3.7/datetime.py'>

In [75]:
start_time = datetime.datetime.now()
np.sum(arr, axis=1)
end_time = datetime.datetime.now()
print(end_time - start_time)

0:00:00.105940


In [76]:
start_time = datetime.datetime.now()
np.sum(arr, axis=0)
end_time = datetime.datetime.now()
print(end_time - start_time)

0:00:00.091421


In [77]:
arr_transposed = arr.T

In [78]:
arr_transposed

array([[       0,    10000,    20000, ..., 99970000, 99980000, 99990000],
       [       1,    10001,    20001, ..., 99970001, 99980001, 99990001],
       [       2,    10002,    20002, ..., 99970002, 99980002, 99990002],
       ...,
       [    9997,    19997,    29997, ..., 99979997, 99989997, 99999997],
       [    9998,    19998,    29998, ..., 99979998, 99989998, 99999998],
       [    9999,    19999,    29999, ..., 99979999, 99989999, 99999999]])

In [79]:
start_time = datetime.datetime.now()
np.sum(arr_transposed, axis=1)
end_time = datetime.datetime.now()
print(end_time - start_time)

0:00:00.084384


In [80]:
start_time = datetime.datetime.now()
np.sum(arr_transposed, axis=0)
end_time = datetime.datetime.now()
print(end_time - start_time)

0:00:00.100797


## numpy.ravel


https://numpy.org/doc/stable/reference/generated/numpy.ravel.html#numpy.ravel


What is the fastest axis of an array?   
https://agilescientific.com/blog/2018/12/28/what-is-the-fastest-axis-of-an-array

https://github.com/agilescientific/notebooks/blob/master/Fastest_dimension_of_array.ipynb

※NumPy配列ndarrayをバイナリファイル（npy, npz）で保存  
https://note.nkmk.me/python-numpy-load-save-savez-npy-npz/