<a href="https://colab.research.google.com/github/hiro106/statistics_ml_cs_learning/blob/main/numpy_indices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://numpy.org/doc/stable/reference/generated/numpy.indices.html

In [1]:
import numpy as np

In [2]:
grid = np.indices((2, 3))

In [3]:
grid.shape

(2, 2, 3)

In [4]:
grid

array([[[0, 0, 0],
        [1, 1, 1]],

       [[0, 1, 2],
        [0, 1, 2]]])

In [5]:
x = np.arange(20).reshape(5, 4)

In [6]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [7]:
row, col = np.indices((2, 3))

In [8]:
row

array([[0, 0, 0],
       [1, 1, 1]])

In [9]:
col

array([[0, 1, 2],
       [0, 1, 2]])

In [10]:
x[row, col]

array([[0, 1, 2],
       [4, 5, 6]])