<a href="https://colab.research.google.com/github/hiro106/statistics_ml_cs_learning/blob/main/numpy_indices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://numpy.org/doc/stable/reference/generated/numpy.indices.html

In [2]:
import numpy as np

In [3]:
grid = np.indices((2, 3))

In [4]:
grid.shape

(2, 2, 3)

In [5]:
grid

array([[[0, 0, 0],
        [1, 1, 1]],

       [[0, 1, 2],
        [0, 1, 2]]])

In [6]:
x = np.arange(20).reshape(5, 4)

In [7]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [8]:
row, col = np.indices((2, 3))

In [9]:
row

array([[0, 0, 0],
       [1, 1, 1]])

In [10]:
col

array([[0, 1, 2],
       [0, 1, 2]])

In [11]:
x[row, col]

array([[0, 1, 2],
       [4, 5, 6]])

In [12]:
x[:2, :3]

array([[0, 1, 2],
       [4, 5, 6]])

In [13]:
i, j = np.indices((2, 3), sparse=True)

In [14]:
i

array([[0],
       [1]])

In [15]:
j

array([[0, 1, 2]])

In [16]:
i, j = np.indices((2, 3))

In [17]:
i

array([[0, 0, 0],
       [1, 1, 1]])

In [18]:
j

array([[0, 1, 2],
       [0, 1, 2]])

## Test with a sample matrix

In [ ]:
idx_test = np.indices((2,3))
idx_test

array([[[0, 0, 0],
        [1, 1, 1]],

       [[0, 1, 2],
        [0, 1, 2]]])

In [ ]:
idx_test.shape

(2, 2, 3)

In [ ]:
idx_test2 = np.indices((2,3,4))
idx_test2

array([[[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]],


       [[[0, 0, 0, 0],
         [1, 1, 1, 1],
         [2, 2, 2, 2]],

        [[0, 0, 0, 0],
         [1, 1, 1, 1],
         [2, 2, 2, 2]]],


       [[[0, 1, 2, 3],
         [0, 1, 2, 3],
         [0, 1, 2, 3]],

        [[0, 1, 2, 3],
         [0, 1, 2, 3],
         [0, 1, 2, 3]]]])

In [ ]:
idx_test2.shape

(3, 2, 3, 4)

In [ ]:
idx_test2

array([[[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]],


       [[[0, 0, 0, 0],
         [1, 1, 1, 1],
         [2, 2, 2, 2]],

        [[0, 0, 0, 0],
         [1, 1, 1, 1],
         [2, 2, 2, 2]]],


       [[[0, 1, 2, 3],
         [0, 1, 2, 3],
         [0, 1, 2, 3]],

        [[0, 1, 2, 3],
         [0, 1, 2, 3],
         [0, 1, 2, 3]]]])

In [ ]:
idx_test2.ravel(order='C')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 0, 0, 0, 0, 1, 1, 1, 1,
       2, 2, 2, 2, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1,
       2, 3, 0, 1, 2, 3])

In [ ]:
idx_test2

array([[[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]],


       [[[0, 0, 0, 0],
         [1, 1, 1, 1],
         [2, 2, 2, 2]],

        [[0, 0, 0, 0],
         [1, 1, 1, 1],
         [2, 2, 2, 2]]],


       [[[0, 1, 2, 3],
         [0, 1, 2, 3],
         [0, 1, 2, 3]],

        [[0, 1, 2, 3],
         [0, 1, 2, 3],
         [0, 1, 2, 3]]]])

In [ ]:
idx_test2.ravel(order='F')

array([0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 2, 0, 1, 2, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 2, 1, 1, 2, 1, 0, 0, 2, 1, 0, 2, 0, 1,
       2, 1, 1, 2, 0, 2, 2, 1, 2, 2, 0, 0, 3, 1, 0, 3, 0, 1, 3, 1, 1, 3,
       0, 2, 3, 1, 2, 3])

In [ ]:
idx_test2_sparse = np.indices((2,3,4), sparse=True)
idx_test2_sparse

(array([[[0]],
 
        [[1]]]), array([[[0],
         [1],
         [2]]]), array([[[0, 1, 2, 3]]]))