<a href="https://colab.research.google.com/github/hiro106/colab_notebooks_for_learning/blob/main/numpy_reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# https://numpy.org/doc/stable/reference/generated/numpy.reshape.html#numpy.reshape

In [2]:
import numpy as np

In [3]:
a = np.zeros((10, 2))

In [4]:
a

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [5]:
b = a.T

In [6]:
b   

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:
c = b.view()

In [8]:
c

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
# About the difference between view and copy
# https://numpy.org/doc/stable/user/basics.copies.html