<a href="https://colab.research.google.com/github/hiro106/statistics-ml-cs-learning/blob/main/PLYMI_Accessing_Data_Along_Multiple_Dimensions_in_an_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# A 0-D array
np.array(8)

array(8)

In [3]:
# A 1-D array, shape-(3,)
np.array([2.3, 0.1, -9.1])

array([ 2.3,  0.1, -9.1])

In [4]:
# A 2-D array, shape-(3, 2)
np.array([[93, 95],
          [84, 100],
          [99, 87]])

array([[ 93,  95],
       [ 84, 100],
       [ 99,  87]])

In [5]:
# A 3-D array, shape-(2, 2, 2)
d3arr = np.array([[[0, 1],
                    [2, 3]],
                    [[4, 5],
                    [6, 7]]])

In [6]:
d3arr

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [7]:
d3arr.shape

(2, 2, 2)

In [8]:
type(d3arr)

numpy.ndarray

In [9]:
simple_array = np.array([2.3, 0.1, -9.1])

In [10]:
simple_array

array([ 2.3,  0.1, -9.1])

In [11]:
simple_array[1]

0.1

In [12]:
simple_array[1:3]

array([ 0.1, -9.1])

In [13]:
# This indexing ends up with an out of bounds error
# simple_array[3]

In [14]:
# using a 1-dimensional array to store the grades
grades = np.array([93, 95, 84, 100, 99, 87])

In [15]:
grades

array([ 93,  95,  84, 100,  99,  87])

In [16]:
# using a 2-dimensional array to store the grades
grades = np.array([[93, 95],
                   [84, 100],
                   [99, 87]])

In [17]:
grades

array([[ 93,  95],
       [ 84, 100],
       [ 99,  87]])

In [18]:
grades.shape

(3, 2)

In [19]:
grades[1, 0]

84

In [20]:
grades[-2, 0]

84

In [21]:
gr1d = grades[0:3, 1]

In [22]:
gr1d.shape

(3,)

In [23]:
gr1d2 = grades[1:, 1]

In [24]:
gr1d2.shape

(2,)

In [25]:
gr2d = grades[:, :1]

In [26]:
gr2d.shape

(3, 1)

In [27]:
gr_neg = grades[:, -1]

In [28]:
gr_neg

array([ 95, 100,  87])

In [29]:
gr_neg.shape

(3,)

In [30]:
grades[0]

array([93, 95])

In [31]:
grades[0, :]

array([93, 95])

In [32]:
d3_array = np.array([[[0, 1],
                      [2, 3]],
                     
                     [[4, 5],
                      [6, 7]]])

In [33]:
d3_array

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [34]:
d3_array[:, 0, 0]

array([0, 4])

In [35]:
d3_array[1]

array([[4, 5],
       [6, 7]])

In [36]:
d3_array[1].shape

(2, 2)

In [37]:
d3_array[1, :, :]

array([[4, 5],
       [6, 7]])

In [38]:
arr = np.array([[[ 0,  1,  2],
                 [ 3,  4,  5],
                 [ 6,  7,  8]],
               
                [[ 9, 10, 11],
                 [12, 13, 14],
                 [15, 16, 17]],
               
                [[18, 19, 20],
                 [21, 22, 23],
                 [24, 25, 26]]])

In [39]:
arr[:, :, 2]

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])

In [40]:
arr[:2, 1, :]

array([[ 3,  4,  5],
       [12, 13, 14]])

In [41]:
arr[0, :2, 2]

array([2, 5])

In [42]:
arr[1, :, ::-1]

array([[11, 10,  9],
       [14, 13, 12],
       [17, 16, 15]])

In [43]:
arr[1, :, ::-1].shape

(3, 3)

In [44]:
arr[1, :, ::-1].size

9

In [45]:
x = np.array(15.2)

In [46]:
x

array(15.2)

In [47]:
x.shape

()

In [48]:
x.size

1

In [49]:
# x[0]

In [50]:
x.item()

15.2

In [51]:
x = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

In [52]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [53]:
x.shape

(3, 4)

In [54]:
x.size

12

In [55]:
x.item

<function ndarray.item>

In [56]:
# x.item()

In [57]:
x.reshape(3, 2, 2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [58]:
x.shape

(3, 4)

In [59]:
x.reshape(3, 2, 2).shape

(3, 2, 2)

In [60]:
x.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [61]:
x.transpose().shape

(4, 3)

In [62]:
x.transpose().reshape(3, 2, 2)

array([[[ 1,  5],
        [ 9,  2]],

       [[ 6, 10],
        [ 3,  7]],

       [[11,  4],
        [ 8, 12]]])

In [63]:
x.transpose().transpose()

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [64]:
x = np.array([0,1,2,3,4,5])

In [65]:
x

array([0, 1, 2, 3, 4, 5])

In [66]:
x.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [67]:
x.transpose()

array([0, 1, 2, 3, 4, 5])

In [68]:
x.shape

(6,)

In [69]:
x.transpose().shape

(6,)

In [70]:
x.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [71]:
x.reshape(6,)

array([0, 1, 2, 3, 4, 5])

In [72]:
x.reshape(1, 6)

array([[0, 1, 2, 3, 4, 5]])

In [73]:
x.reshape(1, 6).shape

(1, 6)

In [74]:
x.shape

(6,)

In [75]:
x.shape = (2, 3)

In [76]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [77]:
x.shape

(2, 3)

In [78]:
x.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [79]:
x.size

6

In [80]:
# x.shape = (2, 2)

In [81]:
np.arange(36)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [82]:
np.arange(36).reshape(3, 4, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [83]:
np.arange(36).reshape(3, 4, -1)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [84]:
np.arange(36).reshape(3, -1, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [85]:
np.arange(36).reshape(-1, 4, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])