<a href="https://colab.research.google.com/github/hiro106/statistics-ml-cs-learning/blob/main/PLYMI_Accessing_Data_Along_Multiple_Dimensions_in_an_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# A 0-D array
np.array(8)

array(8)

In [3]:
# A 1-D array, shape-(3,)
np.array([2.3, 0.1, -9.1])

array([ 2.3,  0.1, -9.1])

In [4]:
# A 2-D array, shape-(3, 2)
np.array([[93, 95],
          [84, 100],
          [99, 87]])

array([[ 93,  95],
       [ 84, 100],
       [ 99,  87]])

In [6]:
# A 3-D array, shape-(2, 2, 2)
d3arr = np.array([[[0, 1],
                    [2, 3]],
                    [[4, 5],
                    [6, 7]]])

In [7]:
d3arr

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [8]:
d3arr.shape

(2, 2, 2)

In [11]:
type(d3arr)

numpy.ndarray

In [12]:
simple_array = np.array([2.3, 0.1, -9.1])

In [13]:
simple_array

array([ 2.3,  0.1, -9.1])

In [14]:
simple_array[1]

0.1

In [15]:
simple_array[1:3]

array([ 0.1, -9.1])

In [16]:
# This indexing ends up with an out of bounds error
# simple_array[3]

IndexError: ignored

In [17]:
# using a 1-dimensional array to store the grades
grades = np.array([93, 95, 84, 100, 99, 87])

In [18]:
grades

array([ 93,  95,  84, 100,  99,  87])

In [19]:
# using a 2-dimensional array to store the grades
grades = np.array([[93, 95],
                   [84, 100],
                   [99, 87]])

In [20]:
grades

array([[ 93,  95],
       [ 84, 100],
       [ 99,  87]])

In [22]:
grades.shape

(3, 2)

In [23]:
grades[1, 0]

84

In [25]:
grades[-2, 0]

84

In [30]:
gr1d = grades[0:3, 1]

In [31]:
gr1d.shape

(3,)

In [32]:
gr1d2 = grades[1:, 1]

In [33]:
gr1d2.shape

(2,)

In [34]:
gr2d = grades[:, :1]

In [36]:
gr2d.shape

(3, 1)

In [38]:
gr_neg = grades[:, -1]

In [44]:
gr_neg

array([ 95, 100,  87])

In [39]:
gr_neg.shape

(3,)

In [42]:
grades[0]

array([93, 95])

In [43]:
grades[0, :]

array([93, 95])

In [40]:
d3_array = np.array([[[0, 1],
                      [2, 3]],
                     
                     [[4, 5],
                      [6, 7]]])

In [41]:
d3_array

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [45]:
d3_array[:, 0, 0]

array([0, 4])

In [46]:
d3_array[1]

array([[4, 5],
       [6, 7]])

In [47]:
d3_array[1].shape

(2, 2)

In [48]:
d3_array[1, :, :]

array([[4, 5],
       [6, 7]])

In [49]:
arr = np.array([[[ 0,  1,  2],
                 [ 3,  4,  5],
                 [ 6,  7,  8]],
               
                [[ 9, 10, 11],
                 [12, 13, 14],
                 [15, 16, 17]],
               
                [[18, 19, 20],
                 [21, 22, 23],
                 [24, 25, 26]]])

In [50]:
arr[:, :, 2]

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])

In [51]:
arr[:2, 1, :]

array([[ 3,  4,  5],
       [12, 13, 14]])

In [52]:
arr[0, :2, 2]

array([2, 5])

In [59]:
arr[1, :, ::-1]

array([[11, 10,  9],
       [14, 13, 12],
       [17, 16, 15]])