<a href="https://colab.research.google.com/github/hiro106/statistics-ml-cs-learning/blob/main/PLYMI_Functions_for_Creating_NumPy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/FunctionsForCreatingNumpyArrays.html

In [1]:
import numpy as np

In [2]:
np.array([i**2 for i in range(5)])

array([ 0,  1,  4,  9, 16])

In [3]:
range(5)

range(0, 5)

In [4]:
print([i for i in range(5)])

[0, 1, 2, 3, 4]


In [5]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [6]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
    
        .. versionadded:: 1.20

In [8]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [9]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [10]:
np.random.normal(1, 5, 10)

array([ 0.31404527,  2.8327892 , -0.03182511, -4.81333557,  8.51914898,
        9.65418872,  4.83617789,  7.93615612, -5.11273203, -2.80511998])

In [11]:
np.array([1.5, 3.20, 5.78], dtype=int)

array([1, 3, 5])

In [12]:
np.array([1., 2., 3.])

array([1., 2., 3.])

In [14]:
np.array([1., 2., 3.]).shape

(3,)

In [15]:
np.array([[1., 2., 3.], [4., 5., 6.]])

array([[1., 2., 3.],
       [4., 5., 6.]])

In [16]:
np.array([[1., 2., 3.], [4., 5., 6.]]).shape

(2, 3)

In [17]:
np.array([[[0]*4]*3]*2)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [18]:
np.array([[[0]*4]*3]*2).shape

(2, 3, 4)

In [19]:
np.array([[1, 2], [3]])

<ipython-input-19-322a9604ebd0>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1, 2], [3]])


array([list([1, 2]), list([3])], dtype=object)

In [21]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.ones((4))

array([1., 1., 1., 1.])

In [23]:
np.ones((4,))

array([1., 1., 1., 1.])

In [24]:
np.arange(0, 10, 1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(-5, 6, 2)

array([-5, -3, -1,  1,  3,  5])

In [27]:
np.arange(6,-5,2)

array([], dtype=int64)