<a href="https://colab.research.google.com/github/hiro106/statistics-ml-cs-learning/blob/main/PLYMI_Functions_for_Creating_NumPy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/FunctionsForCreatingNumpyArrays.html

In [1]:
import numpy as np

In [2]:
np.array([i**2 for i in range(5)])

array([ 0,  1,  4,  9, 16])

In [3]:
range(5)

range(0, 5)

In [6]:
print([i for i in range(5)])

[0, 1, 2, 3, 4]


In [8]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [9]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
help(np.ones)

In [13]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [14]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])