<a href="https://colab.research.google.com/github/hiro106/statistics-ml-cs-learning/blob/main/PLYMI_Introducing_the_ND_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/usr/local/lib/python3.8/dist-packages/numpy/__init__.py'>

In [3]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
# An ND-array belongs to the type `numpy.ndarray`
type(x)

numpy.ndarray

In [6]:
isinstance(x, np.ndarray)

True

In [7]:
x = x.reshape(3, 3)

In [8]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
np.power(x, 2)

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [10]:
type(x)

numpy.ndarray

In [11]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
np.mean(x, axis=1)

array([1., 4., 7.])

In [16]:
x ** np.array([0., 1., 2.])

array([[ 1.,  1.,  4.],
       [ 1.,  4., 25.],
       [ 1.,  7., 64.]])

In [17]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
x * np.array([0., 1., 2.])

array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])

In [20]:
x[:2, :3]

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
x[x % 2 == 0] *= -1

In [22]:
x

array([[ 0,  1, -2],
       [ 3, -4,  5],
       [-6,  7, -8]])